<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Covid and reasons to protect people from covid, and how to solve">
    <meta name="keywords" content="Covid, corona, virus, virus corona">
    <title>Vaccination</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="../styles/main.css">
</head>
<body>
  <div class="main-container">
               <!-- Render header-->
              <?php 
              include '../Layouts/header.php';
              ?>

               <!-- Render main -->
               <div class="contactusphp">
                <!--Section: Contact v.2-->
              
<p style="color:white;margin-top:20px;font-size:30px">Some question ?</p>
</div>

<div class="accordion" id="accordionExample" style="background-color:#17C2EC;border-radius:20px;padding:20px">
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
      How do vaccines work? Do they work against viruses and bacteria?
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
      <div class="accordion-body">
      Vaccines work to prime your immune system against future “attacks” by a particular disease. There are vaccines against both viral and bacterial pathogens, or disease-causing agents.

When a pathogen enters your body, your immune system generates antibodies to try to fight it off. Depending on the strength of your immune response and how effectively the antibodies fight off the pathogen, you may or may not get sick.

If you do fall ill, however, some of the antibodies that are created will remain in your body playing watchdog after you’re no longer sick. If you’re exposed to the same pathogen in the future, the antibodies will “recognize” it and fight it off.

Vaccines work because of this function of the immune system. They’re made from a killed, weakened, or partial version of a pathogen. When you get a vaccine, whatever version of the pathogen it contains isn’t strong or plentiful enough to make you sick, but it’s enough for your immune system to generate antibodies against it. As a result, you gain future immunity against the disease without having gotten sick: if you’re exposed to the pathogen again, your immune system will recognize it and be able to fight it off.

Some vaccines against bacteria are made with a form of the bacteria itself. In other cases, they may be made with a modified form of a toxin generated by the bacteria. Tetanus, for example, is not directly caused by the Clostridium tetani bacteria. Instead, its symptoms are primarily caused by tetanospasmin, a toxin generated by that bacterium. Some bacterial vaccines are therefore made with a weakened or inactivated version of the toxin that actually produces symptoms of illness. This weakened or inactivated toxin is called a toxoid. A tetanus immunization, for example, is made with tetanospasmin toxoid.
         </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
      Why aren't all vaccines 100% effective?
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
      <div class="accordion-body">
      Vaccines are designed to generate an immune response that will protect the vaccinated individual during future exposures to the disease. Individual immune systems, however, are different enough that in some cases, a person’s immune system will not generate an adequate response. Therefore, he or she will not be effectively protected after immunization.That said, the effectiveness of most vaccines is high. After receiving the second dose of the MMR vaccine (measles, mumps and rubella) or the standalone measles vaccine, 99.7% of vaccinated individuals are immune to measles. The inactivated polio vaccine offers 99% effectiveness after three doses. The varicella (chickenpox) vaccine is between 85% and 90% effective in preventing all varicella infections, but 100% effective in preventing moderate and severe chicken pox.
        </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
      Why are there so many vaccines?
      </button>
    </h2>
    <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
      <div class="accordion-body">
      Currently, the U.S. childhood vaccination schedule for children between birth and six years of age recommends immunizations for 14 different diseases. Some parents worry this number seems high, particularly since some vaccine-preventable diseases are now extremely rare in the United States.

Each disease for which vaccinations are recommended can cause serious illness or death in unvaccinated populations, and could quickly begin to appear again if vaccination rates dropped. The United States has seen mumps outbreaks in recent years, since vaccination rates have dropped, with severe complications and hospitalizations required for some patients. And before the introduction of the Hib (Haemophilus Influenzae Type b) vaccine, Hib meningitis affected more than 12,000 American children annually, killing 600 and leaving many others with seizures, deafness, and developmental disabilities. After the vaccine was introduced, the number of deaths from Hib dropped to fewer than 10 per year.

Each vaccine on the schedule continues to be recommended because of the risks posed by wild infection.  
    </div>
    </div>
  </div>
  
</div>


<div class="accordion" id="accordionPanelsStayOpenExample" style="background-color:#17C2EC;border-radius:20px;padding:20px;margin-top:20px">
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="false" aria-controls="panelsStayOpen-collapseOne">
      Is natural immunity better than vaccine-acquired immunity?
      </button>
    </h2>
    <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show">
      <div class="accordion-body">
      In some cases, natural immunity is longer-lasting than the immunity gained from vaccination. The risks of natural infection, however, outweigh the risks of immunization for every recommended vaccine. For example, wild measles infection causes encephalitis (inflammation of the brain) for one in 1,000 infected individuals. Overall, measles infection kills two of every 1,000 infected individuals. In contrast, the combination MMR (measles, mumps and rubella) vaccine results in a severe allergic reaction only once in every million vaccinated individuals, while preventing measles infection. The benefits of vaccine-acquired immunity extraordinarily outweigh the serious risks of natural infection. (For more on this topic, see our Understanding Risks activity.)

Additionally, the Hib (Haemophilus influenzae type b) and tetanus vaccines actually provide more effective immunity than natural infection.   </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
      Why do some vaccines require boosters?
      </button>
    </h2>
    <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse">
      <div class="accordion-body">
      It is unclear why the length of acquired immunity varies with different vaccines. Some offer lifelong immunity with only one dose, while others require boosters to maintain immunity. Recent research has suggested that the persistence of immunity against a particular disease may depend on the speed with which that disease typically progresses through the body. If a disease progresses rapidly, the immune system’s memory response (that is, the “watchdog antibodies” generated after a previous infection or vaccination) may not respond quickly enough to prevent infection—unless they’ve been “reminded” about the disease fairly recently and are already watching for it. Boosters serve as a “reminder” to your immune system.

Research continues on the persistence of immunity generated by vaccines.    </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false" aria-controls="panelsStayOpen-collapseThree">
      My child was invited to a chickenpox party. Would it be better for my child to get the chickenpox this way? Why do we vaccinate against a mild disease like chickenpox?
      </button>
    </h2>
    <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse">
      <div class="accordion-body">
      The idea of “pox parties” is generally tied to the perception of chickenpox as a harmless illness. Before the varicella vaccine became available, however, chickenpox infections required 10,000 hospitalizations and caused more than 100 deaths each year in the United States. Exposing a child to wild chickenpox puts him at risk for a severe case of the disease.

Even uncomplicated cases of chickenpox cause children to miss a week or more of school, with a caregiver missing work to care for the sick child.[1] Natural infection also means a risk of infecting others: while successful vaccination protects a child against chickenpox without this risk, children infected with chickenpox naturally are contagious. They can spread the disease to other people—not just other children, but also adults, who have a higher risk of complications from the disease.

Meanwhile, vaccination for chickenpox typically prevents future infection with the disease. In rare cases where individuals do not develop adequate protection from vaccination to prevent future infection, chickenpox infection is typically mild, results in fewer symptoms, and ends more quickly than natural infection. (People with this mild form are contagious, however, and should take care not to expose others to the virus.) </div>
    </div>
  </div>
</div>


<form class="row g-3" style="width:50%;background-color:#17C2EC;margin-top:20px;border-radius:20px;padding:20px">
  <div class="col-md-6">
    <label for="inputEmail4" class="form-label">Email</label>
    <input type="email" class="form-control" id="inputEmail4">
  </div>
  <div class="col-md-6">
    <label for="inputPassword4" class="form-label">Password</label>
    <input type="password" class="form-control" id="inputPassword4">
  </div>
  <div class="col-12">
    <label for="inputAddress" class="form-label">Address</label>
    <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
  </div>
  <div class="col-12">
    <label for="inputAddress2" class="form-label">Address 2</label>
    <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">
  </div>
  <div class="col-md-6">
    <label for="inputCity" class="form-label">City</label>
    <input type="text" class="form-control" id="inputCity">
  </div>
  <div class="col-md-4">
    <label for="inputState" class="form-label">State</label>
    <select id="inputState" class="form-select">
      <option selected>Choose...</option>
      <option>...</option>
    </select>
  </div>
  <div class="col-md-2">
    <label for="inputZip" class="form-label">Zip</label>
    <input type="text" class="form-control" id="inputZip">
  </div>
  <div class="col-12">
    <div class="form-check">
      <input class="form-check-input" type="checkbox" id="gridCheck">
      <label class="form-check-label" for="gridCheck">
        Check me out
      </label>
    </div>
  </div>
  <div class="col-12">
    <button type="submit" class="btn btn-primary">Sign in</button>
  </div>
</form>

          <?php 

             include '../Layouts/footer.php';
             ?>
</div>


<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
              <!-- Render footer-->

 
</body>
</html>